# Habilitar backup

ENABLED=true

# O que será salvo

BACKUP_DATABASE=true
BACKUP_UPLOADS=true
BACKUP_FULL_PROJECT=false

# Quantos dias manter

RETENTION_DAYS=180

# Futuro

# BACKUP_REMOTE=true
# BACKUP_REMOTE_TARGET=nas